# Generated by Django 3.0.6 on 2020-05-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200521_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrine',
            name='descricao',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='categoria',
            field=models.CharField(choices=[('Informatica', 'Informática'), ('Celulares', 'Celulares'), ('Moda', 'Moda')], max_length=20),
        ),
    ]
