# Generated by Django 3.0.6 on 2020-05-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200525_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vitrine',
            name='descricao',
            field=models.TextField(default='', null=True),
        ),
    ]
