# Generated by Django 3.0.6 on 2020-05-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20200527_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='bairro',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='perfil',
            name='cep',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='perfil',
            name='ponto_referencia',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='perfil',
            name='rua',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cidade',
            field=models.CharField(max_length=100),
        ),
    ]
