# Generated by Django 3.0.6 on 2020-05-28 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_perfil_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encomenda',
            name='comentario_encomenda',
        ),
        migrations.AddField(
            model_name='encomenda',
            name='comentario',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
    ]
