# Generated by Django 3.0.6 on 2020-09-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200528_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrine',
            name='acessos',
            field=models.BigIntegerField(default=0),
        ),
    ]
