# Generated by Django 3.0.6 on 2020-09-25 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_avaliacao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacao',
            name='user',
        ),
    ]
