# Generated by Django 3.0.6 on 2020-09-22 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_vitrine_acessos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitrine',
            name='acessos',
            field=models.BigIntegerField(default=0),
        ),
    ]
