# Generated by Django 3.0.6 on 2020-09-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_avaliacao_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='quantidade',
            field=models.BigIntegerField(default=0),
        ),
    ]
