# Generated by Django 3.0.6 on 2020-09-25 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_avaliacao_quantidade'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacao',
            old_name='nota',
            new_name='media_nota',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='somaTotal_nota',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
