# Generated by Django 3.0.6 on 2020-10-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20201002_1539'),
        ('blog', '0019_auto_20201002_1542'),
    ]

    operations = [
    ]
