# Generated by Django 3.0.6 on 2020-10-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_merge_20201002_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='user.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='produto.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='foto',
            field=models.ImageField(blank=True, default='vitrine.png', upload_to=''),
        ),
    ]
