# Generated by Django 3.0.6 on 2020-10-02 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20201002_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, default='user.png', upload_to='perfis'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='foto',
            field=models.ImageField(blank=True, default='produto.jpeg', upload_to='produtos'),
        ),
        migrations.AlterField(
            model_name='vitrine',
            name='foto',
            field=models.ImageField(blank=True, default='vitrine.png', upload_to='vitrines'),
        ),
    ]
